runmode: debug                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
expireTime: 86400
issuer: go-mall-server
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  drive: mysql
  enabled: true
  url: homestead:secret@(192.168.10.10:3306)/cola_mall?charset=utf8&parseTime=true&loc=Asia%2FShanghai
  maxIdleConnection: 100
  maxOpenConnection: 130
